---
title: "main"
output: html_document
date: "2022-11-20"
author: "Jonas Barth, Mattia Castaldo, Matteo Migliarino"
---

```{r}
install.packages('VGAM')
install.packages('ggplot2')
install.packages('tidyverse')
install.packages("dplyr")
install.packages("colorspace")
library('VGAM')
library('ggplot2')
library('tidyverse')
library('dplyr')
library('colorspace')
```

## Hyperparameters

```{r}
n = 1000
eps = 0.1
m = n^(1 / (2 + 1))
```

## Original Histogram

```{r}
b_sample = rbeta(n=n, 10, 10)

original_hist = hist(b_sample, plot=F, breaks=m-1)

plot(original_hist)
```

## Create Perturbed Histogram

```{r}

l_perturbe = function(h, l_mean = 0, l_scale = 8 / (0.001 ^ 2)) {
    perturbed_hist = h
    lap_sample = rlaplace(length(perturbed_hist$counts), location = l_mean, scale = l_scale)
    
    # Add the laplace sample to D_j
    perturbed_hist$counts = perturbed_hist$counts + lap_sample
    
    # If we end up with a negative number, we choose 0 instead. Same as max(0, D_j)
    perturbed_hist$counts[perturbed_hist$counts <= 0] = 0

    # Normalise D_j over the sum of all bins
    perturbed_hist$counts = perturbed_hist$counts / sum(perturbed_hist$counts)
    if (any(is.na(perturbed_hist$counts))) {
        perturbed_hist$counts = rep(0, length(perturbed_hist$counts))
    }
    
    # Also update the density, divide q_hat by 1/m
    perturbed_hist$density = perturbed_hist$counts / (1 / m)
    
    return(perturbed_hist)
}
perturbed_hist = l_perturbe(original_hist, l_scale = 8 / (eps^2))
plot(perturbed_hist)

```

## Simulation

```{r}
n_values = c(100,1000)
eps_values = c(0.1, 0.001)
bins_values = seq(5, 50, 5)

M = 100
out = data.frame()

mise_sim = function(n, n_bins, eps, sim_size, dist=function(n) rbeta(n, 10,10)) {
    
    out = data.frame()
    
    for (m in 1:sim_size) {
        # sample from beta
        b_sample = dist(n=n)

        # create original hist
        original_hist = hist(b_sample, plot=F, breaks=n_bins - 1)
        
        d_original = stepfun(original_hist$breaks, c(0, original_hist$density, 0))

        # create perturbed hist
        perturbed_hist = l_perturbe(original_hist, l_scale = 8 / (eps^2))
        
        d_perturbed = stepfun(perturbed_hist$breaks, c(0, perturbed_hist$density, 0))
        
        # calculate mise original
        mise_original = integrate(function(x) (dbeta(x, 10, 10) - d_original(x))^2, 0, 1, subdivisions = 1000)$value

        # calculate mise perturbed
        mise_perturbed = integrate(function(x) (dbeta(x, 10, 10) - d_perturbed(x))^2, 0, 1, subdivisions = 1000)$value
        
        out = rbind(out, data.frame(m=m, n=n, eps=eps, bins=n_bins, mise_original=mise_original, mise_perturbed=mise_perturbed))
    }
    
    return(out)
}


out = data.frame()

for (n in n_values) {
    for (eps in eps_values) {
        for (n_bins in bins_values) {
            sim_result = mise_sim(n, n_bins, eps, sim_size = M)
            out = rbind(out, sim_result)
        }
    }
}

out
```

## Plotting

```{r}
out$mise_diff = abs(out$mise_original - out$mise_perturbed)

data_group <- out %>%                                 # Group data
  group_by(eps, n, bins) %>%
  dplyr::summarize(mise_mean = mean(mise_diff), mise_min = min(mise_diff), mise_max = max(mise_diff)) %>% 
  as.data.frame()
data_group


# n = 100, eps = 0.1
data1 = subset(data_group, data_group$n == 100 & data_group$eps == 0.1)

# n = 100, eps = 0.001
data2 = subset(data_group, data_group$n == 100 & data_group$eps == 0.001)

# n = 1000, eps = 0.1
data3 = subset(data_group, data_group$n == 1000 & data_group$eps == 0.1)

# n = 1000, eps = 0.001
data4 = subset(data_group, data_group$n == 1000 & data_group$eps == 0.001)
```

## Plotting with ggplot
```{r}
h = ggplot(data1, aes(data1$bins))
h + 
    geom_ribbon(aes(ymin = data1$mise_min, ymax = data1$mise_max), fill = "#32a852", alpha = 0.3) +
    geom_line(aes(y = data1$mise_mean)) +
    geom_ribbon(aes(ymin = data2$mise_min, ymax = data2$mise_max), fill = "grey60", alpha = 0.3) +
    geom_line(aes(y = data2$mise_mean)) +
    geom_ribbon(aes(ymin = data3$mise_min, ymax = data3$mise_max), fill = "grey50", alpha = 0.3) +
    geom_line(aes(y = data3$mise_mean)) +
    geom_ribbon(aes(ymin = data4$mise_min, ymax = data4$mise_max), fill = "grey40", alpha = 0.3) +
    geom_line(aes(y = data4$mise_mean))
```

## Plotting with standard R
```{r}

colours = rainbow_hcl(4)
lwd = 4

plot(NULL,
     xlim = c(min(bins_values), max(bins_values)),
     ylim = c(min(data_group$mise_mean), max(data_group$mise_mean)),
     ylab = "Mean MISE Differences",
     xlab = "Number of bins",
     main = "Mean MISE Differences over 100 Simulations")
lines(data1$bins, data1$mise_mean, type = "l", lwd = lwd, col = colours[1])
lines(data2$bins, data2$mise_mean, type = "l", lwd = lwd, col = colours[2])
lines(data3$bins, data3$mise_mean, type = "l", lwd = lwd, col = colours[3])
lines(data4$bins, data4$mise_mean, type = "l", lwd = lwd, col = colours[4])
legend("topright", 
       legend=c("n = 100, eps = 0.1", "n = 100, eps = 0.001", "n = 1000, eps = 0.1", "n = 1000, eps = 0.001"), 
       col = colours,
       lwd = 4)
```


# 2.2 Samplng from a different distribution
We now sample from:
$$
p_X(x) = \pi \cdot \text{dbeta}(x | \alpha_1, \beta_1) + (1 -\pi )\cdot \text{dbeta}(x | \alpha_2, \beta_2)
$$
```{r}
func = function(n, pi =.5) pi * rbeta(n,.5,.3) + (1 - pi) * rbeta(n,.5,.1) 
h=hist(func(1000), plot=F)
plot(h, main='Density of p[X]',xlab = '')
```
```{r}
h_perturbed=l_perturbe(h)

plot(h_perturbed, main='Perturbed Histogram of p[X]', xlab='')
```


```{r}
pi_values<-c(.25,.5,.75)
out_new = data.frame()


for (n in n_values) {
    for (eps in eps_values) {
        for (n_bins in bins_values) {
            for (pi in pi_values)   {
                sim_result = mise_sim(n, n_bins, eps, sim_size = M, dist=func)
                out_new = rbind(out_new, sim_result)
            }
        }
    }
}

out_new
```

